# Generated by Django 5.0.7 on 2024-07-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date_last_modifed_alter_post_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Кателогия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
