# Generated by Django 5.0.7 on 2024-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_last_modifed',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
