# Generated by Django 5.0.7 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_date_last_modifed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_last_modifed',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
